import * as React from "react";
import { IntroMovie } from "./introFilm.class";

export const introFilmData: IntroMovie[] = [
  {
    _id: 1,
    name: "Prites of the Caribbean: Dead Mem Tell No Tables",
    penName: "Prites of the Caribbean: Dead Mem Tell No Tables",
    trailerLink: "https://www.youtube.com/embed/uC9qU3X1JgM",
    image: "/film/supperman.jpg",
    description: "Prites of the Caribbean: Dead Mem Tell No Tables",
    dateRelease: "Prites of the Caribbean: Dead Mem Tell No Tables",
    rate: 10,
    groupID: "GP5",
    //bonus
    types: ["Fantasy", "Adventure", "Thriller"],
    timeTickets: ["12:30", "13:30", "14:30", "15:30"],
    index: 0,
  },
  // {
  //   _id: 2,
  //   name: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   penName: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   trailerLink: "https://www.youtube.com/embed/uC9qU3X1JgM",
  //   image: "/film/aquaman.jpg",
  //   description: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   dateRelease: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   rate: 10,
  //   groupID: "GP5",
  //   //bonus
  //   types: ["Fantasy", "Adventure", "Thriller"],
  //   timeTickets: ["12:30", "13:30", "14:30", "15:30"],
  //   index: 1,
  // },
  // {
  //   _id: 3,
  //   name: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   penName: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   trailerLink: "https://www.youtube.com/embed/uC9qU3X1JgM",
  //   image: "/film/supperman.jpg",
  //   description: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   dateRelease: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   rate: 10,
  //   groupID: "GP5",
  //   //bonus
  //   types: ["Fantasy", "Adventure", "Thriller"],
  //   timeTickets: ["12:30", "13:30", "14:30", "15:30"],
  //   index: 2,
  // },
  // {
  //   _id: 4,
  //   name: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   penName: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   trailerLink: "https://www.youtube.com/embed/uC9qU3X1JgM",
  //   image: "/film/aquaman.jpg",
  //   description: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   dateRelease: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   rate: 10,
  //   groupID: "GP5",
  //   //bonus
  //   types: ["Fantasy", "Adventure", "Thriller"],
  //   timeTickets: ["12:30", "13:30", "14:30", "15:30"],
  //   index: 3,
  // },
  // {
  //   _id: 5,
  //   name: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   penName: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   trailerLink: "https://www.youtube.com/embed/uC9qU3X1JgM",
  //   image: "/film/supperman.jpg",
  //   description: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   dateRelease: "Prites of the Caribbean: Dead Mem Tell No Tables",
  //   rate: 10,
  //   groupID: "GP5",
  //   //bonus
  //   types: ["Fantasy", "Adventure", "Thriller"],
  //   timeTickets: ["12:30", "13:30", "14:30", "15:30"],
  //   index: 4,
  // },
];